[project]
name = "fpl-optimizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rhys Hegyi", email = "rhys-hegyi@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pulp>=3.3.2",
    "requests>=2.34.2",
]

[project.scripts]
fpl = "fpl_optimizer:main"
fpl-optimizer = "fpl_optimizer:main"

[build-system]
requires = ["uv_build>=0.11.1,<0.12.0"]
build-backend = "uv_build"
